"use client";
import Image from "next/image";
import { ArrowLeft, Check, ChevronRight } from "lucide-react";
import { motion } from "framer-motion";
import type { Frame } from "@/types";
import { Button } from "./ui/Button";

export function FrameSelector({ frames, selected, onSelect, onContinue, onBack }: { frames: Frame[]; selected: Frame | null; onSelect: (frame: Frame) => void; onContinue: () => void; onBack: () => void }) {
  return <main id="conteudo" className="relative z-10 mx-auto min-h-dvh max-w-6xl px-4 py-6 safe-top safe-bottom"><header className="mb-6 flex items-center gap-4"><button onClick={onBack} className="grid size-12 place-items-center rounded-full bg-white/75" aria-label="Voltar ao início"><ArrowLeft/></button><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#07567f]">Passo 1 de 3</p><h1 className="display text-3xl sm:text-4xl">Escolha sua moldura</h1></div></header>
    <div className="grid gap-6 lg:grid-cols-[1fr_.72fr]"><section className="grid grid-cols-2 gap-3 sm:gap-5" aria-label="Molduras disponíveis">{frames.map((frame, index) => <motion.button initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .05 }} key={frame.id} onClick={() => onSelect(frame)} aria-pressed={selected?.id === frame.id} className={`glass relative overflow-hidden rounded-[1.5rem] p-2 text-left transition ${selected?.id === frame.id ? "ring-4 ring-[#0876ad]" : "hover:-translate-y-1"}`}><div className={`relative w-full overflow-hidden rounded-[1.1rem] bg-[#b9e2f2] ${frame.aspectRatio === "1:1" ? "aspect-square" : frame.aspectRatio === "9:16" ? "aspect-[9/16]" : "aspect-[4/5]"}`}><Image src={frame.previewUrl} alt={`Prévia da moldura ${frame.name}`} fill className="object-contain"/></div><div className="p-3"><span className="font-bold">{frame.name}</span><span className="mt-1 block text-sm text-[#43647a]">Formato {frame.aspectRatio}</span></div>{selected?.id === frame.id && <span className="absolute right-4 top-4 grid size-9 place-items-center rounded-full bg-[#07567f] text-white"><Check className="size-5"/></span>}</motion.button>)}</section>
      <aside className="glass sticky top-5 hidden h-fit rounded-[2rem] p-5 lg:block">{selected ? <><div className={`relative mx-auto max-h-[60dvh] max-w-sm overflow-hidden rounded-[1.5rem] bg-[#a8d9ec] ${selected.aspectRatio === "1:1" ? "aspect-square" : selected.aspectRatio === "9:16" ? "aspect-[9/16]" : "aspect-[4/5]"}`}><Image src={selected.previewUrl} alt={`Moldura ${selected.name} ampliada`} fill className="object-contain"/></div><h2 className="display mt-5 text-2xl">{selected.name}</h2><p className="mt-1 text-[#43647a]">Proporção {selected.aspectRatio}</p></> : <div className="grid min-h-72 place-items-center text-center text-[#43647a]">Toque em uma moldura para ver a prévia.</div>}</aside>
    </div><div className="sticky bottom-3 z-20 mt-6"><Button onClick={onContinue} disabled={!selected} className="w-full shadow-2xl sm:mx-auto sm:flex sm:max-w-md">Usar esta moldura <ChevronRight/></Button></div></main>;
}
