"use client";
import Image from "next/image";
import { AnimatePresence, motion } from "framer-motion";
import { Expand, Pause, Play, Shuffle, Snowflake } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { Photo } from "@/types";

export function LiveSlideshow({ initialPhotos, initialInterval }: { initialPhotos: Photo[]; initialInterval: number }) {
  const [photos, setPhotos] = useState(initialPhotos); const [index, setIndex] = useState(0); const [paused, setPaused] = useState(false); const [shuffle, setShuffle] = useState(false); const [seconds, setSeconds] = useState(initialInterval);
  const next = useCallback(() => setIndex(current => photos.length < 2 ? 0 : shuffle ? (current + 1 + Math.floor(Math.random() * (photos.length - 1))) % photos.length : (current + 1) % photos.length), [photos.length, shuffle]);
  useEffect(() => { if (paused) return; const id = setInterval(next, seconds * 1000); return () => clearInterval(id); }, [next, paused, seconds]);
  useEffect(() => { const id = setInterval(async () => { const response = await fetch("/api/gallery", { cache: "no-store" }); if (response.ok) setPhotos((await response.json()).photos); }, 12_000); return () => clearInterval(id); }, []);
  const current = photos[index % Math.max(photos.length, 1)]; const options = useMemo(() => [5,8,12,15], []);
  return <main id="conteudo" className="relative grid min-h-dvh overflow-hidden bg-[#031d33] text-white">{current ? <AnimatePresence mode="wait"><motion.div key={current.id} initial={{ opacity: 0, scale: 1.025 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0 }} transition={{ duration: .7 }} className="absolute inset-0"><Image src={current.publicUrl} alt="Foto da festa em apresentação" fill priority className="object-contain"/><div className="absolute inset-0 -z-10 scale-110 bg-cover bg-center opacity-20 blur-3xl" style={{ backgroundImage: `url(${current.publicUrl})` }}/></motion.div></AnimatePresence> : <div className="m-auto text-center"><Snowflake className="mx-auto size-20 opacity-70"/><h1 className="display mt-6 text-5xl">A magia começa em instantes</h1><p className="mt-4 text-xl text-white/75">As fotos aprovadas aparecerão aqui automaticamente.</p></div>}<div className="absolute bottom-5 left-1/2 z-20 flex -translate-x-1/2 items-center gap-2 rounded-full bg-black/45 p-2 opacity-25 backdrop-blur transition hover:opacity-100 focus-within:opacity-100"><button onClick={() => setPaused(value => !value)} className="grid size-12 place-items-center rounded-full hover:bg-white/15" aria-label={paused ? "Continuar apresentação" : "Pausar apresentação"}>{paused ? <Play/> : <Pause/>}</button><button onClick={() => setShuffle(value => !value)} aria-pressed={shuffle} className={`grid size-12 place-items-center rounded-full ${shuffle ? "bg-white text-[#082f55]" : "hover:bg-white/15"}`} aria-label="Embaralhar fotos"><Shuffle/></button><select value={seconds} onChange={event => setSeconds(Number(event.target.value))} className="h-11 rounded-full bg-white/15 px-3" aria-label="Intervalo entre fotos">{options.map(value => <option className="text-black" key={value} value={value}>{value}s</option>)}</select><button onClick={() => document.documentElement.requestFullscreen?.()} className="grid size-12 place-items-center rounded-full hover:bg-white/15" aria-label="Entrar em tela cheia"><Expand/></button></div></main>;
}
