"use client";
import Link from "next/link";
import { Camera, Images, LogOut, QrCode, Settings, SlidersHorizontal } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import type { EventConfig, Frame, Photo } from "@/types";
import { AdminPhotoGrid } from "./AdminPhotoGrid";
import { AdminFrameManager } from "./AdminFrameManager";
import { AdminSettings } from "./AdminSettings";
import { QRCodeGenerator } from "./QRCodeGenerator";
type Tab = "photos" | "frames" | "settings" | "qr";
export function AdminDashboard() { const [tab, setTab] = useState<Tab>("photos"); const [data, setData] = useState<{ event: EventConfig; frames: Frame[]; photos: Photo[]; configured: boolean } | null>(null); const load = useCallback(async () => { const response = await fetch("/api/admin/data", { cache: "no-store" }); if (response.ok) setData(await response.json()); }, []); useEffect(() => { void load(); }, [load]); if (!data) return <main className="grid min-h-dvh place-items-center"><span className="size-12 animate-spin rounded-full border-4 border-[#07567f] border-t-transparent" aria-label="Carregando painel"/></main>; const tabs: [Tab,string,React.ReactNode][] = [["photos","Fotos",<Images key="a"/>],["frames","Molduras",<SlidersHorizontal key="b"/>],["settings","Configurações",<Settings key="c"/>],["qr","QR Code",<QrCode key="d"/>]]; return <main id="conteudo" className="min-h-dvh bg-[#f1f9fc] pb-12"><header className="sticky top-0 z-30 border-b bg-white/90 px-4 py-3 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3"><div><span className="display text-xl">Uma Aventura Congelante</span><span className="hidden text-sm text-[#43647a] sm:block">Painel administrativo</span></div><div className="flex gap-2"><Link href="/" className="ice-button ice-secondary !min-h-11 !px-3"><Camera className="size-4"/><span className="hidden sm:inline">Site</span></Link><form action="/api/admin/logout" method="post"><button className="ice-button ice-secondary !min-h-11 !px-3"><LogOut className="size-4"/><span className="hidden sm:inline">Sair</span></button></form></div></div></header><div className="mx-auto max-w-7xl p-4 sm:p-6"><nav className="mb-6 flex gap-2 overflow-x-auto pb-2" aria-label="Seções administrativas">{tabs.map(([key,label,icon]) => <button key={key} onClick={() => setTab(key)} aria-current={tab === key ? "page" : undefined} className={`ice-button whitespace-nowrap !min-h-11 ${tab === key ? "ice-primary" : "ice-secondary"}`}>{icon}{label}</button>)}</nav>{!data.configured && <div role="alert" className="mb-6 rounded-2xl border border-[#d6a514] bg-[#fff8db] p-4 font-semibold">Modo demonstração: configure o Supabase para persistir fotos e alterações.</div>}<h1 className="display mb-5 text-3xl sm:text-4xl">{tabs.find(item => item[0] === tab)?.[1]}</h1>{tab === "photos" && <AdminPhotoGrid photos={data.photos} frames={data.frames} onRefresh={load}/>} {tab === "frames" && <AdminFrameManager eventId={data.event.id} frames={data.frames} onRefresh={load}/>} {tab === "settings" && <AdminSettings event={data.event} onRefresh={load}/>} {tab === "qr" && <QRCodeGenerator/>}</div></main>; }
