"use client";
import Image from "next/image";
import JSZip from "jszip";
import { Check, Copy, Download, EyeOff, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import type { Frame, Photo } from "@/types";
import { Button } from "../ui/Button";
import { Modal } from "../ui/Modal";

export function AdminPhotoGrid({ photos, frames, onRefresh }: { photos: Photo[]; frames: Frame[]; onRefresh: () => void }) {
  const [selected, setSelected] = useState<string[]>([]); const [frame, setFrame] = useState("all"); const [order, setOrder] = useState("new"); const [open, setOpen] = useState<Photo | null>(null); const [busy, setBusy] = useState(false);
  const filtered = useMemo(() => photos.filter(photo => frame === "all" || photo.frameId === frame).sort((a,b) => order === "new" ? +new Date(b.createdAt) - +new Date(a.createdAt) : +new Date(a.createdAt) - +new Date(b.createdAt)), [photos, frame, order]);
  async function patch(id: string, status: Photo["status"]) { const response = await fetch(`/api/admin/photos/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); if (response.ok) { toast.success("Foto atualizada."); onRefresh(); } else { toast.error("Falha ao atualizar."); } }
  async function remove(id: string) { if (!confirm("Excluir esta foto definitivamente?")) return; const response = await fetch(`/api/admin/photos/${id}`, { method: "DELETE" }); if (response.ok) { toast.success("Foto excluída."); onRefresh(); } else { toast.error("Falha ao excluir."); } }
  async function zipSelected() { const targets = selected.length ? photos.filter(photo => selected.includes(photo.id)) : filtered; if (!targets.length) return; setBusy(true); try { const zip = new JSZip(); await Promise.all(targets.map(async (photo, index) => { const response = await fetch(photo.publicUrl); if (!response.ok) throw new Error(); zip.file(`foto-${String(index + 1).padStart(3,"0")}.jpg`, await response.blob()); })); const blob = await zip.generateAsync({ type: "blob" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "fotos-aventura-congelante.zip"; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch { toast.error("Não foi possível montar o ZIP. Verifique as permissões CORS do Storage."); } finally { setBusy(false); } }
  return <section><div className="mb-5 flex flex-wrap gap-3"><select value={frame} onChange={event => setFrame(event.target.value)} className="h-12 rounded-full border bg-white px-4" aria-label="Filtrar por moldura"><option value="all">Todas as molduras</option>{frames.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={order} onChange={event => setOrder(event.target.value)} className="h-12 rounded-full border bg-white px-4" aria-label="Ordenar fotos"><option value="new">Mais recentes</option><option value="old">Mais antigas</option></select><Button variant="secondary" onClick={zipSelected} disabled={busy}><Download className="size-4"/> {busy ? "Preparando…" : selected.length ? `Baixar ${selected.length} em ZIP` : "Baixar todas em ZIP"}</Button></div>{filtered.length === 0 ? <div className="rounded-3xl border border-dashed p-12 text-center">Nenhuma foto encontrada.</div> : <div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-4">{filtered.map(photo => <article key={photo.id} className="overflow-hidden rounded-2xl border bg-white shadow-sm"><button onClick={() => setOpen(photo)} className="relative block aspect-[4/5] w-full bg-[#dff5ff]"><Image src={photo.publicUrl} alt="Foto do evento" fill className="object-cover"/></button><div className="p-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected.includes(photo.id)} onChange={() => setSelected(value => value.includes(photo.id) ? value.filter(id => id !== photo.id) : [...value, photo.id])} className="size-5"/> Selecionar</label><span className="mt-2 block text-xs font-bold uppercase">{photo.status === "approved" ? "Aprovada" : photo.status === "pending" ? "Pendente" : "Oculta"}</span><div className="mt-2 flex flex-wrap gap-1"><button onClick={() => patch(photo.id, "approved")} className="grid size-10 place-items-center rounded-full bg-[#def5e9]" aria-label="Aprovar"><Check className="size-4"/></button><button onClick={() => patch(photo.id, "hidden")} className="grid size-10 place-items-center rounded-full bg-[#e9edf0]" aria-label="Ocultar"><EyeOff className="size-4"/></button><button onClick={() => navigator.clipboard.writeText(photo.publicUrl).then(() => toast.success("Link copiado."))} className="grid size-10 place-items-center rounded-full bg-[#dff5ff]" aria-label="Copiar link"><Copy className="size-4"/></button><button onClick={() => remove(photo.id)} className="grid size-10 place-items-center rounded-full bg-[#fde8e7] text-[#9f2d28]" aria-label="Excluir"><Trash2 className="size-4"/></button></div></div></article>)}</div>}<Modal open={Boolean(open)} onClose={() => setOpen(null)} title="Visualizar foto">{open && <Image src={open.publicUrl} alt="Foto ampliada" width={open.width} height={open.height} className="mx-auto max-h-[68dvh] w-auto rounded-xl"/>}</Modal></section>;
}
