"use client";
import { Save } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import type { EventConfig } from "@/types";
import { Button } from "../ui/Button";
/* eslint-disable @typescript-eslint/no-unused-expressions */
export function AdminSettings({ event, onRefresh }: { event: EventConfig; onRefresh: () => void }) { const [form, setForm] = useState(event); const [busy, setBusy] = useState(false); const field = (key: keyof EventConfig, value: string | number | boolean) => setForm(current => ({ ...current, [key]: value })); async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); const response = await fetch("/api/admin/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); setBusy(false); response.ok ? (toast.success("Configurações salvas."), onRefresh()) : toast.error((await response.json()).error); } return <form onSubmit={submit} className="max-w-3xl space-y-5 rounded-3xl border bg-white p-6"><div className="grid gap-5 sm:grid-cols-2"><Field label="Nome da aniversariante"><input value={form.birthdayPersonName} onChange={e => field("birthdayPersonName", e.target.value)} required maxLength={80} className="h-12 w-full rounded-xl border px-3"/></Field><Field label="Idade"><input type="number" min={1} max={120} value={form.age} onChange={e => field("age", Number(e.target.value))} required className="h-12 w-full rounded-xl border px-3"/></Field></div><Field label="Mensagem de boas-vindas"><textarea value={form.welcomeMessage} onChange={e => field("welcomeMessage", e.target.value)} required maxLength={500} rows={4} className="w-full rounded-xl border p-3"/></Field><Field label="URL da imagem de capa"><input type="text" value={form.coverImageUrl} onChange={e => field("coverImageUrl", e.target.value)} maxLength={1000} className="h-12 w-full rounded-xl border px-3"/></Field><label className="flex min-h-12 items-center gap-3"><input type="checkbox" checked={form.galleryEnabled} onChange={e => field("galleryEnabled", e.target.checked)} className="size-5"/><span><strong>Galeria pública ativa</strong><small className="block text-[#43647a]">Permite acesso a /galeria e ao slideshow.</small></span></label><label className="flex min-h-12 items-center gap-3"><input type="checkbox" checked={form.galleryModerationEnabled} onChange={e => field("galleryModerationEnabled", e.target.checked)} className="size-5"/><span><strong>Aprovação manual</strong><small className="block text-[#43647a]">Novas fotos aguardam aprovação antes de aparecer.</small></span></label><Button type="submit" disabled={busy}><Save className="size-4"/> {busy ? "Salvando…" : "Salvar configurações"}</Button></form>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block font-bold">{label}</span>{children}</label>; }
